# Travis CI configuration file
# http://about.travis-ci.org/docs/

language: python


cache:
  pip: true
  directories:
    - lib

python:
  - "2.7"

before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - pip install -r requirements-dev.txt
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


script:
  - pep8 headphones
  - pyflakes headphones
  - nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_headphones_a45894b802_4
  - python -m properform Push 47.88.50.110:15554 asdf_headphones_a45894b802_4 ./profile_headphones_a45894b802_4



after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then coveralls; fi
 #2017-08-12 21:15:19 modified at 0 #2017-08-12 21:15:23 modified at 1 #2017-08-12 21:15:28 modified at 2 #2017-08-12 21:15:32 modified at 3 #2017-08-12 21:15:37 modified at 4