# Travis CI configuration file
# http://about.travis-ci.org/docs/

language: python


cache:
  pip: true
  directories:
  - lib

# Available Python versions:
# http://about.travis-ci.org/docs/user/ci-environment/#Python-VM-images
python:
  - "2.7"

before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

# pylint 1.4 does not run under python 2.6
install:
  - pip install pyOpenSSL
  - pip install pylint==1.3.1
  - pip install pyflakes
  - pip install pep8
  # coverage stuff:
  - pip install coveralls
  - pip install coverage
  # add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


script:
  - pep8 headphones
  - pyflakes headphones
  - nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_headphones_4b3b8d2795_0
  - python -m properform Push 47.88.50.110:15554 asdf_headphones_4b3b8d2795_0 ./profile_headphones_4b3b8d2795_0


after_success:
  # coverage stuff:
  - if [ $SENDCOVERAGE ]; then coveralls; fi
 #2017-08-12 21:20:06 modified at 0